#!/bin/sh

if [ -z "${GARRIGA_HOME}" ]
then
  echo "GARRIGA_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${GARRIGA_HOME}/lib" \
-m com.io7m.garriga.main/com.io7m.garriga.main.Main \
"$@"
