FROM docker.io/library/eclipse-temurin:${com.io7m.oci.versionTemurin}

ENV PATH="/garriga/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/java/openjdk/bin"
ENV GARRIGA_HOME="/garriga"

COPY garriga /garriga

LABEL "org.opencontainers.image.authors"="Mark Raynsford"
LABEL "org.opencontainers.image.description"="AlertManager → Matrix Alert Relay"
LABEL "org.opencontainers.image.licenses"="ISC"
LABEL "org.opencontainers.image.source"="https://www.github.com/io7m/garriga"
LABEL "org.opencontainers.image.title"="Garriga"
LABEL "org.opencontainers.image.url"="https://www.io7m.com/software/garriga"
LABEL "org.opencontainers.image.version"="${project.version}"
LABEL "org.opencontainers.image.revision"="${buildNumber}"

ENTRYPOINT ["/garriga/bin/garriga"]
